- README.md
Signed-off-by: Yoan Blanc <yoan.blanc@exoscale.ch>
> doc: unbreak the tabs/spaces mix

- .travis.yml
> travis: add travis

- .travis.yml
- exoip.go
- src/exoip/api.go
- src/exoip/engine.go
- src/exoip/logging.go
- src/exoip/metadata.go
- src/exoip/network.go
- src/exoip/peer.go
- src/exoip/state.go
- src/exoip/types.go
Signed-off-by: Yoan Blanc <yoan.blanc@exoscale.ch>
> travis: fix gofmt

- logging.go
> logging: avoid using syslog if it fails

- cmd/exoip.go
fixes #22 
```
$ kill -SIGTERM 1567
exoip [INFO   ] claimed ip 159.100.244.188 on nic 62b071c7-1519-46b3-8ec8-3d718f1bb2fd
exoip [INFO   ] got sig: terminated, releasing the Nic and stopping.
exoip [INFO   ] released ip 159.100.244.188
```
> cmd: listen to SIGTERM,SIGINT

- cmd/exoip/main.go
- engine.go
> regrab the NIC at certain intervals

- Makefile
- cmd/exoip/main.go
- engine.go
- types.go
Switching to/from master/backup via signals
```console
$ kill -SIGUSR1 ...
exoip [INFO   ] got sig: user defined signal 1
exoip [INFO   ] new priority: 11
$ kill -SIGUSR1 ...
exoip [INFO   ] got sig: user defined signal 1
exoip [INFO   ] new priority: 10
exoip [INFO   ] swiching state to StateMaster
exoip [INFO   ] claimed ip 159.100.244.188 on nic 62b071c7-1519-46b3-8ec8-3d718f1bb2fd
$ kill -SIGUSR2 ...
exoip [INFO   ] got sig: user defined signal 2
exoip [INFO   ] new priority: 11
exoip [INFO   ] swiching state to StateBackup
exoip [INFO   ] released ip 159.100.244.188 from nic 62b071c7-1519-46b3-8ec8-3d718f1bb2fd
```
> Sig usr1 usr2 to control the priority

- Gopkg.lock
- Gopkg.toml
- cmd/exoip/main.go
- version.go
> cli: print version

- Makefile
- engine.go
reobtain the nic after killing other's nic (split-brain)
> Reobtain nic

- engine.go
listing all the VMs is a bad idea as CS paginates and orders randomly
https://github.com/exoscale/exoip/commit/839bd2252074f0a866aac7a138291f3b87206542
> engine: do not list all the vms

- Dockerfile
- Makefile
- README.md
- cmd/exoip/main.go
- engine.go
- metadata.go
- peer.go
- types.go
blank error messages are bland
> engine: bind source UDP connection to eth0

- Jenkinsfile
requires https://github.com/exoscale/jenkins-pipeline/pull/4
> jenkins: tag docker image

- engine.go
> engine: update priority sent in payload

- engine.go
Signed-off-by: Yoan Blanc <yoan.blanc@exoscale.ch>
> engine: fix some log messages

- .gometalinter.json
- Jenkinsfile
- api.go
- assert.go
- cmd/exoip/main.go
- engine.go
- logging.go
- metadata.go
- payload.go
@jpmenil is there a nicer way to do the jenkinsfile? (thanks)
> Gometalinter

- Gopkg.lock
- Gopkg.toml
- README.md
~~*this is broken*~~
this requires a release of egoscale though
> dep: bump to egoscale master

- .dockerignore
- Dockerfile.exoscale
- Jenkinsfile
> jenkinsfile: use dockerfile using bionic

- .goreleaser.yml
- .travis.yml
> travis: install nfpm

- cmd/exoip/main.go
Using `-A` or `-D` were displaying `-W` related debug content. cc @JessicaToscani
> main: only show watch info when watching

- .travis.yml
codeclimate was never activated on this project.
> travis: use cc-reporter-id

- Dockerfile
- go.mod
- vendor/github.com/exoscale/egoscale/.travis.yml
- vendor/github.com/exoscale/egoscale/CHANGELOG.md
- vendor/github.com/exoscale/egoscale/addresses.go
- vendor/github.com/exoscale/egoscale/affinity_groups.go
- vendor/github.com/exoscale/egoscale/instance_groups.go
- vendor/github.com/exoscale/egoscale/isos.go
- vendor/github.com/exoscale/egoscale/isos_response.go
- vendor/github.com/exoscale/egoscale/networks.go
- vendor/github.com/exoscale/egoscale/nics.go
- vendor/github.com/exoscale/egoscale/request.go
- vendor/github.com/exoscale/egoscale/request_type.go
- vendor/github.com/exoscale/egoscale/reversedns.go
- vendor/github.com/exoscale/egoscale/runstatus.go
- vendor/github.com/exoscale/egoscale/runstatus_event.go
- vendor/github.com/exoscale/egoscale/runstatus_incident.go
- vendor/github.com/exoscale/egoscale/runstatus_maintenance.go
- vendor/github.com/exoscale/egoscale/runstatus_service.go
- vendor/github.com/exoscale/egoscale/security_groups.go
- vendor/github.com/exoscale/egoscale/snapshots.go
- vendor/github.com/exoscale/egoscale/ssh_keypairs.go
- vendor/github.com/exoscale/egoscale/tags.go
- vendor/github.com/exoscale/egoscale/templates.go
- vendor/github.com/exoscale/egoscale/uuid.go
- vendor/github.com/exoscale/egoscale/version.go
- vendor/github.com/exoscale/egoscale/virtual_machines.go
- vendor/modules.txt
> Update egoscale / dockerfile
